version: "3.7"
services:
  chip:
    build:
      context: ./
      dockerfile: Dockerfile
    image: chip-library
    container_name: chip-library
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - default
    ports:
      - "80:80"
